### PR TITLE
DSND-531: Add Maven Checkstyle plugin

### PR DESCRIPTION
**Pull request by VaughanJackson123**

### CODE REVIEW

**Comment by VaughanJackson123** [comment]
* We currently have a suggestion that we configure both CheckStyle and Sonar as part of the app initialisation. 
* Is this correct, or should we handle Sonar as part of the CI tasks?

**Comment by sroberts2** [comment]
If you are configuring Checkstyle can you make sure it's using the Google style standards not the default Sun style standards?

**Comment by VaughanJackson123** [comment]
> If you are configuring Checkstyle can you make sure it's using the Google style standards not the default Sun style standards?

It's configured to use the Companies House Checkstyle config.  It is using this file: https://github.com/companieshouse/java-checkstyle-config/blob/master/src/main/resources/companieshouse_checks.xml. This comment at the top of that file suggests it is therefore using Google style standards:

> Checkstyle configuration that checks the Google coding conventions from Google Java Style
>     that can be found at https://google.github.io/styleguide/javaguide.html.

**Comment by VaughanJackson123** [comment]
> * We currently have a suggestion that we configure both CheckStyle and Sonar as part of the app initialisation.
> * Is this correct, or should we handle Sonar as part of the CI tasks?

@caismith-ch has confirmed that the SonarQube configuration is typically done as part of app initialisation stories like this one. 

That will be covered in a separate PR.

**Review by caismith-ch — APPROVED** [review]

**Pull request merged**
